version: "3"
services:
  pilot-mysql:
    container_name: "pilot-mysql"
    image: "mysql:5.7"
    environment:
      MYSQL_DATABASE: pilot
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_ROOT_HOST: "%"
      TZ: "Asia/Seoul"
    command:
      -- character-set-server=utf8mb4
      -- collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
  pilot-jenkins:
    container_name: "pilot-jenkins-build"
    image: "jenkins/jenkins"
    environment:
      TZ: "Asia/Seoul"
    ports:
      - "7000:8080"
      - "50000:50000"
    volumes:
      - ./jenkins:/var/jenkins_home
  pilot-jenkins-batch-launcher:
    container_name: "pilot-jenkins-batch-launcher"
    image: "jenkins/jenkins"
    environment:
      TZ: "Asia/Seoul"
    ports:
      - "8000:8080"
      - "50001:50000"
    volumes:
      - ./jenkins/batch/launcher:/var/jenkins_home
      - ./jenkins/workspace/pilot-batch-builder/pilot-batch/build/libs/:/var/jankins_home/deploy
