spring:
  jpa:
    show-sql: true
    properties:
      hibernate.default_batch_fetch_size: 500
      hibernate.dialect: org.hibernate.dialect.MySQL57Dialect
      hibernate.dialect.storage_engine: innodb
      hibernate.format_sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: anfro123!
    url: jdbc:mysql://siyoung-pilot-rds4.cki3kdutd3oc.ap-northeast-2.rds.amazonaws.com:3306/pilot?serverTimezone=UTC&characterEncoding=UTF-8
server:
  port: 5000
